# Generated by Django 4.1.7 on 2023-11-28 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Имя', max_length=60)),
                ('image', models.ImageField(upload_to='static/image')),
            ],
        ),
        migrations.CreateModel(
            name='Ordering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('номер телефона', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назввание')),
                ('img', models.ImageField(null=True, upload_to='static/image')),
                ('brand', models.CharField(max_length=20)),
                ('color', models.CharField(choices=[('white', 'white'), ('red', 'red'), ('green', 'green'), ('yellow', 'yellow'), ('blue', 'blue')], default='a', max_length=80, verbose_name='Цвет')),
                ('speed', models.IntegerField(verbose_name='Скорость')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_app.category', verbose_name='Категория')),
            ],
        ),
    ]
